[package]
name = "mnstr2023"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.4"
nanoid = "0.4.0"
rocket = "0.5.0-rc.3"
shuttle-rocket = "0.29.0"
shuttle-runtime = "0.29.0"
tokio = "1.33.0"
