[package]
name = "mnstr2023"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoid = "0.4.0"
rocket = "0.5.0-rc.3"
rocket_contrib = "0.4.11"
serde = "1.0.189"
serde_json = "1.0.107"
tokio = "1.33.0"
